/*
 * This source file was generated by the Gradle 'init' task
 */
package com.mapt.demo.backend

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
open class DemoBackendApplication

fun main(args: Array<String>) {
    runApplication<DemoBackendApplication>(*args)
}
