# Spring Boot Configuration
spring.application.name=ArucoGeometryFeedback
server.port=8080
server.address=0.0.0.0

# Logging
logging.level.root=INFO
logging.level.com.mapt.demo.backend=DEBUG

# Server configuration
server.servlet.context-path=/
server.error.include-message=always
server.error.include-binding-errors=always

# Tryb magazynowy - sciezka pliku CSV ze zdarzeniami pobrano/zlozono
warehouse.csv.path=events.csv

